# Generated by Django 5.1.2 on 2026-05-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clause',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Legal', 'Legal'), ('Finance', 'Finance'), ('Liability', 'Liability'), ('Operational', 'Operational')], default='Legal', max_length=32)),
                ('risk', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=8)),
                ('version', models.CharField(default='v1.0', max_length=16)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=8)),
            ],
        ),
    ]
