# Generated by Django 5.2.14 on 2026-05-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clauses', '0002_clause_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='clause',
            name='ai_recommendation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clause',
            name='deviation_rule',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clause',
            name='escalation_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clause',
            name='mandatory',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clause',
            name='restricted_terms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clause',
            name='standard_rule',
            field=models.TextField(blank=True, null=True),
        ),
    ]
