# Generated by Django 5.1.2 on 2026-05-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clauses', '0003_clause_ai_recommendation_clause_deviation_rule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clause',
            name='clause_category',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='clause',
            name='clause_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
