# Generated by Django 5.1.2 on 2026-05-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clauses', '0004_clause_clause_category_clause_clause_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='clause',
            name='restricted_terms_conditions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clause',
            name='risk_level',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=255),
        ),
        migrations.AddField(
            model_name='clause',
            name='standard_rule_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clause',
            name='clause_category',
            field=models.CharField(choices=[('Confidentiality', 'Confidentiality'), ('Payment Terms', 'Payment Terms'), ('Liability', 'Liability'), ('Indemnity', 'Indemnity'), ('Governing Law', 'Governing Law'), ('Termination', 'Termination'), ('Data Privacy', 'Data Privacy'), ('Intellectual Property', 'Intellectual Property'), ('Renewal', 'Renewal'), ('Service Levels', 'Service Levels'), ('Audit Rights', 'Audit Rights'), ('Insurance', 'Insurance'), ('Compliance', 'Compliance'), ('Security', 'Security'), ('Force Majeure', 'Force Majeure'), ('Assignment', 'Assignment'), ('Subcontracting', 'Subcontracting')], default='Confidentiality', max_length=255),
        ),
        migrations.AlterField(
            model_name='clause',
            name='clause_name',
            field=models.CharField(max_length=255),
        ),
    ]
