# Generated by Django 5.1.2 on 2026-05-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clauses', '0005_clause_restricted_terms_conditions_clause_risk_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clause',
            name='ai_recommendation',
            field=models.TextField(default='No AI recommendation provided'),
        ),
        migrations.AlterField(
            model_name='clause',
            name='clause_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='clause',
            name='deviation_rule',
            field=models.TextField(default='No deviation rule provided'),
        ),
        migrations.AlterField(
            model_name='clause',
            name='restricted_terms_conditions',
            field=models.TextField(default='No restricted terms provided'),
        ),
        migrations.AlterField(
            model_name='clause',
            name='standard_rule_value',
            field=models.TextField(default='No standard rule provided'),
        ),
    ]
