# Generated by Django 5.1.2 on 2026-05-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('vendor', models.CharField(max_length=255)),
                ('expiry', models.DateField()),
                ('redlines', models.PositiveIntegerField(default=0)),
                ('version', models.CharField(default='v1.0', max_length=16)),
                ('risk', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=8)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired')], default='Active', max_length=8)),
                ('uploaded', models.DateField(auto_now_add=True)),
                ('clauses', models.PositiveIntegerField(default=0)),
                ('file', models.FileField(blank=True, null=True, upload_to='contracts/')),
            ],
        ),
    ]
