# Generated by Django 5.2.14 on 2026-05-18 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clauses', '0001_initial'),
        ('contracts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('external_document', models.CharField(blank=True, max_length=255)),
                ('summary', models.TextField()),
                ('exported_at', models.DateTimeField(auto_now_add=True)),
                ('contract_left', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='left_comparisons', to='contracts.contract')),
                ('contract_right', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='right_comparisons', to='contracts.contract')),
                ('exported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RedlineSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(max_length=255)),
                ('recommendation', models.TextField()),
                ('risk', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=8)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Open', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clause', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clauses.clause')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redline_suggestions', to='contracts.contract')),
            ],
        ),
    ]
