# Generated by Django 5.1.2 on 2026-05-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_contractcomparison_redlinesuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractcomparison',
            name='comparison_detail',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contractcomparison',
            name='external_file',
            field=models.FileField(blank=True, null=True, upload_to='comparisons/'),
        ),
        migrations.AddField(
            model_name='redlinesuggestion',
            name='reviewer_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contractcomparison',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
