# Generated by Django 5.1.2 on 2026-05-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_contract_ai_cache_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='redlinesuggestion',
            name='ai_recommendation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='redlinesuggestion',
            name='deviation_rule',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='redlinesuggestion',
            name='restricted_terms',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='redlinesuggestion',
            name='standard_rule',
            field=models.TextField(blank=True, default=''),
        ),
    ]
