# Generated by Django 5.2.14 on 2026-05-18 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharepoint', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharePointSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed'), ('Warning', 'Warning')], default='Success', max_length=8)),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='sharepoint.sharepointconfig')),
            ],
        ),
    ]
