# Generated by Django 5.1.2 on 2026-05-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=128)),
                ('target', models.CharField(max_length=255)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('ip', models.CharField(default='Internal', max_length=64)),
            ],
        ),
    ]
